name: Political SNAFU
favicon: null
layout_spectrum: 0.7449
typography_spectrum: 0.922841037157923
title: Political SNAFU
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0e3d2'
    - '#c5b59e'
    - '#284b71'
    - '#d3272c'
    - '#768994'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
